<?php
header('Content-Type: text/html; charset=UTF-8');
require('wp-load.php');

//'ID'             
//'post_author'             '713'
//'post_date'             
//'post_date_gmt'             
//'post_content'             ''
//'post_content_filtered'             ''
//'post_title'             'Gerardo MIJARES'
//'post_excerpt'             ''
// 'post_status'             'publish'
// 'post_type'             'aspirantes'
// 'comment_status'             'closed'
// 'ping_status'             'closed'
//'post_password'             ''
//'post_name'             ''
//'to_ping'             ''
//'pinged'             ''
//'post_modified'             ''
//'post_modified_gmt'             ''
//'post_parent' super optional             ''
//'menu_order'             ''
//'post_mime_type'             ''
// 'guid'.             'http://localhost/vxm/?aspirantes=1811'




// 'post_author'             713
// 'post_title'             'Gerardo MIJARES'
// 'post_status'             'publish'
// 'post_type'             'aspirantes'
// 'comment_status'             'closed'
// 'ping_status'             'closed'
// 'guid'              'http://localhost/vxm/?aspirantes='.$autogend_id




$full_names = array('GERARDO MIJARES','RICARDO GONZALEZ');
$emails = array('gerardo.mijares@lapsusdev.com', 'ricardo.gonz@lapsusdev.com');
$start_id = 1820;

// insert_aspirantes_posts($full_names, $emails, $start_id);
function DO_IT_POSTS(){
    $CSVfp = fopen("LIBROPRUEBACSV.csv", "r");
    if($CSVfp !== FALSE) {
        while(! feof($CSVfp)) {
            $data = fgetcsv($CSVfp, 1000, ",");

            array_push($full_names, $data['0'].$data['1']);
            array_push($emails, $data['6']);

        }
    }
    fclose($CSVfp);
    print_r($full_names);
    print_r($emails);
}

function insert_aspirantes_posts($full_names, $emails, $start_id){
    
    $autogend_id = $start_id;

    for ($i = 0; $i < sizeof($full_names); $i++){

        $full_name = $full_names[$i];
        $email = $emails[$i];
        
        // Create post object
        $my_post = array();

        // Create $my_post object
        // $my_post['ID'] = $autogend_id;
        $my_post['post_author'] = 713;
        $my_post['post_title'] = $full_name;
        $my_post['post_status'] = 'publish';
        $my_post['post_type'] = 'aspirantes';
        $my_post['comment_status'] = 'closed';
        $my_post['ping_status'] = 'closed';
        $my_post['guid'] = 'http://localhost/vxm/?aspirantes='.$autogend_id;

        $my_post['post_content'] = $email; // remember to erase post content of posts table somehow

        // Insert the post into the database
        wp_insert_post($my_post); 

        // Increment autogenerated id
        $autogend_id = $autogend_id + 1;
    }

    echo '<h4>Started at id: '.$start_id.'</h4>';
    echo '<h4>Finished at id: '.($autogend_id - 1).'</h4>';

}




// La funcion principal va a recibir un arreglo de arreglos, donde los subarreglos contendran la informacion de los aspirantes
// DO_IT es la funcion principal para meter la meta_data
// abre el archivo csv, luego pasa esa informacion a $aspirante_info
// y lueog llama a insert_aspirante_posts_meta

function DO_IT(){
    $CSVfp = fopen("LIBROPRUEBACSV.csv", "r");
    if($CSVfp !== FALSE) {
        while(! feof($CSVfp)) {
            $data = fgetcsv($CSVfp, 1000, ",");

            $aspirante_info['primer_nombre'] = $data['0'];
            $aspirante_info['apellidos'] = $data['1'];
            $aspirante_info['pais'] = $data['2'];
            $aspirante_info['estado'] = $data['3'];
            $aspirante_info['municipio'] = $data['4'];
            $aspirante_info['telefono'] = $data['5'];
            $aspirante_info['email'] = $data['6'];
        
            print_r($aspirante_info);
            insert_aspirante_posts_meta($aspirante_info);
        }
    }
    fclose($CSVfp);
}







// $handle = fopen ("LIBROPRUEBACSV.csv","r");
// // echo '<table border="1"><tr><td>First name</td><td>Last name</td></tr><tr>';
// while ($data = fgetcsv ($handle, 1000, ";")) {
//         $data = array_map("utf8_encode", $data); //added
//         $num = count ($data);
//         for ($c=0; $c < $num; $c++) {
//             // output data
//             echo "<td>$data[$c]</td>";
//         }
//         echo "</tr><tr>";
// }



// $aspirante_info['primer_nombre'] = $data['0'];
// $aspirante_info['apellidos'] = $data['1'];
// $aspirante_info['pais'] = $data['2'];
// $aspirante_info['estado'] = $data['3'];
// $aspirante_info['municipio'] = $data['4'];
// $aspirante_info['telefono'] = $data['5'];
// $aspirante_info['email'] = $data['6'];


// this function is intended to be run after adding aspirantes to posts table, aspirante info 
// is intended to have the 7 fields of informaction from excel datasheet
// database will be queried in posts table for people with the same $aspirante_info['email']
// once we got the post, we'll retrieve the $post_id and call insert_aspirantes_post_meta
function insert_aspirante_posts_meta($aspirante_info){

    $args = array('post_content' => $aspirante_info['email']);
    $query = new WP_Query($args);

    // Actually do the inserting into table thing
    if($query->have_posts()){
        while($query->have_posts()){     // this while is expected to have only one iteration since we are entering the info of one aspirante

                $post_id = get_the_ID();

                $aspirante_meta['primer_nombre'] = $aspirante_info['primer_nombre'];
                $aspirante_meta['apellidos'] = $aspirante_info['apellidos'];
                $aspirante_meta['pais'] = $aspirante_info['pais'];
                $aspirante_meta['estado'] = $aspirante_info['estado'];
                $aspirante_meta['municipio'] = $aspirante_info['municipio'];
                $aspirante_meta['telefono'] = $aspirante_info['telefono'];
                $aspirante_meta['email'] = $aspirante_info['email'];

                insert_aspirante_post_meta($post_id, $aspirante_meta);

                // Erase auxiliary emails in post content if info was successfully put inserted into table
                $args = array();
                $args['post_content'] = "";
                wp_update_post($post_id, $args);
        }
    } else {
        echo "<h4>".$aspirante_info['email']." wasn't added since it wasn't found on database</h4>";
    }
}






function insert_aspirante_post_meta($post_id, $aspirante_meta){
    
    $aspirante = array();

    $aspirante['first_name'] = $aspirante_meta['primer_nombre'];
    $aspirante['apellidos'] = $aspirante_meta['apellidos'];
    $aspirante['pagado'] = '';
    $aspirante['importe'] = '';
    $aspirante['lugar_cert'] = '';
    $aspirante['pais'] = $aspirante_meta['pais'];
    $aspirante['edo'] = $aspirante_meta['estado']; //ver si esta disponible la informacion
    $aspirante['municipio'] = $aspirante_meta['municipio']; //ver si esta disponible la informacion
    $aspirante['colonia'] = '';
    $aspirante['calle'] = '';
    $aspirante['telefono1'] = String($aspirante_meta['telefono']); //settype($var1, "string");
    $aspirante['telefono2'] = '';
    $aspirante['email'] = $aspirante_meta['email'];
    $aspirante['niveo'] = '';
    $aspirante['notas'] = '';
    $aspirante['post_id'] = String($post_id); //para el wp-old-slug;
    $aspirante['user_id'] = '';

    $meta_keys = array(
        'OFC-1-ANombresDelAspirante',   
        '_OFC-1-ANombresDelAspirante',   
        'OFC-1-AApellidosDelAspirante',  
        '_OFC-1-AApellidosDelAspirante',    
        'OFC-1-AYaPagoSuCertificacion',     
        '_OFC-1-AYaPagoSuCertificacion',      
        'OFC-1-AImporteQuePagoEnSuCertificación',     
        '_OFC-1-AImporteQuePagoEnSuCertificación',    
        'OFC-1-ALugarDeCertificacion',   
        '_OFC-1-ALugarDeCertificacion', 
        'OFI-1-APais',     
        '_OFI-1-APais',    
        'OFI-1-AEstado',   
        '_OFI-1-AEstado',     
        'OFI-1-AMunicipio',    
        '_OFI-1-AMunicipio',  
        'OFI-1-AColonia',     
        '_OFI-1-AColonia',    
        'OFI-1-ACalle',       
        '_OFI-1-ACalle',      
        'OFI-1-ATelefono1',    
        '_OFI-1-ATelefono1',    
        'OFI-1-ATelefono2',     
        '_OFI-1-ATelefono2',     
        'OFI-1-AEmail',        
        '_OFI-1-AEmail',        
        'numero_instructor_veo',   
        '_numero_instructor_veo',  
        'aspirante_admin_note',    
        '_aspirante_admin_note',    
        '_validate_email',          
        '__validate_email',         
        '_wp_old_slug',        
        'tipo_de_aspirante',        
        '_tipo_de_aspirante',           
        '_status',          
        '_userid' 
    );

    $meta_values = array(
        $aspirante['first_name'],
        'field_580832340ea65',
        $aspirante['apellidos'],
        'field_580832340eae0',
        $aspirante['pagado'],
        'field_580832340eb5e',
        $aspirante['importe'],
        'field_580832340ebdc',
        $aspirante['lugar_cert'],
        'field_58083c1b823fd',
        $aspirante['pais'],
        'field_5806e51f740dd',
        $aspirante['edo'],
        'field_5806ed35740de',
        $aspirante['municipio'],
        'field_5806edff740df',
        $aspirante['colonia'],
        'field_5806ef93740e0',
        $aspirante['calle'],
        'field_5806f0c2740e1',
        $aspirante['telefono1'],
        'field_5806f0f4740e2',
        $aspirante['telefono2'],
        'field_5806f12b740e3',
        $aspirante['email'],
        'field_5806f16d740e5',
        $aspirante['niveo'],
        'field_5a8b05f27f7c2',
        $aspirante['notas'],
        'field_5a8ddbe3c7094',
        '',
        '_validate_email',
        $aspirante['post_id'],
        'instructor',
        'field_580ee593ab24b',
        '00',
        $aspirante['user_id']
    );

    if(sizeof($meta_values) === sizeof($meta_keys)){
        for ($k = 0; $k <= 10; $k++){
            add_post_meta( $post_id, $meta_keys[$k], $meta_values[$k] );
        }
    }

}
































